#! /bin/sh
### BEGIN INIT INFO
# Provides:          grenzschnitte
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop "Grenzschnitte" web server.
# Description:       Grenzschnitte is the Web UI for the LetsMT/OPUS resource repository.
### END INIT INFO

. /lib/lsb/init-functions
. /usr/local/etc/repository/conf.sh

# configuration variables
homedir=/usr/local/lib/grenzschnitte
cmd=$homedir/bin/webinterface
params="daemon"
piddir=/var/run/letsmt
pidfile=$piddir/grenzschnitte.pid
logdir=$LETSMTLOG_DIR
logfile=$logdir/grenzschnitte.log

unset LANGUAGE
export PATH="$PATH:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin"

# dispatch the command
case "$1" in
    start)
        log_daemon_msg "Starting the Grenzschnitte webserver" || true
        mkdir -p $piddir
        mkdir -p $logdir
        touch $logfile
        chown $LETSMTUSER $logfile

        if [ -n "$(pidofproc -p $pidfile $cmd)" ] ; then
            printf "   ...server already running -\n"
            log_end_msg 1 || true
            exit 1
        elif [ -e $pidfile ] ; then
            printf "   ...warning: deleting stale PID file!\n"
            rm $pidfile
        fi

        start-stop-daemon --start --quiet --pidfile $pidfile --make-pidfile \
            --background --chdir $homedir --chuid $LETSMTUSER --exec $cmd -- $params
        log_end_msg $? || true
    ;;
    stop)
        log_daemon_msg "Stopping the Grenzschnitte webserver" || true
        start-stop-daemon --stop --quiet --oknodo --retry 1 --user $LETSMTUSER --pidfile $pidfile
        pid=$(pidofproc -p $pidfile perl)
        if [ -n "$pid" -a -d /proc/$pid/ ]; then
            log_warning_msg 'Process hangs' || true
            exit 1
        else
            rm -f $pidfile
            log_end_msg 0 || true
            exit 0
        fi
    ;;
    restart)
        $0 stop
        $0 start
    ;;
    reload|hup)
        log_daemon_msg "Telling the Grenzschnitte webserver to reload for log rotation"
        pid=$(pidofproc -p $pidfile perl)
        if [ -n "$pid" ]; then
            printf "   ...sending hangup signal to process #%s\n" $pid
            kill -HUP "$pid"
            log_end_msg 0 || true
        else
            log_warning_msg 'No process found' || true
            exit 1
        fi
    ;;
    status)
        pid=$(pidofproc -p $pidfile $cmd)
        if [ -n "$pid" ]; then
            status_of_proc -p $pidfile $cmd "Grenzschnitte webserver" \
                && exit 0 || exit $?
        else
            printf " * The Grenzschnitte webserver is not running\n" $database
        fi
    ;;
    *)
        printf 'Usage: %s {start|stop|restart|reload|hup|status}\n' $0
        exit 1
esac


exit 0

#
# This file is part of LetsMT! Resource Repository.
#
# LetsMT! Resource Repository is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# LetsMT! Resource Repository is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with LetsMT! Resource Repository.  If not, see
# <http://www.gnu.org/licenses/>.
#